# File: /318-aspell/config/aspell.conf
# ──────────────────────────────────────────────────────────────────────────────
# 🔤 aspell
# ──────────────────────────────────────────────────────────────────────────────
