# File: /3n-phpactor/config/phpactor.yml
# ──────────────────────────────────────────────────────────────────────────────
# 🅿️ Phpactor
# ──────────────────────────────────────────────────────────────────────────────

{}
