# File: /305-alacritty/config/alacritty.toml
# ──────────────────────────────────────────────────────────────────────────────
# 🔺 Alacritty
# ──────────────────────────────────────────────────────────────────────────────

## ─────────────────────────────────────────────────────────────────────────────
## 🎨 Theme.
## ─────────────────────────────────────────────────────────────────────────────

import = [
    "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

## ─────────────────────────────────────────────────────────────────────────────
## ♻️  Environment variables.
## ─────────────────────────────────────────────────────────────────────────────

[env]

# Needed for tmux
TERM = "screen-256color"

## ─────────────────────────────────────────────────────────────────────────────
## 🪟 Window.
## ─────────────────────────────────────────────────────────────────────────────

[window]

## Avoid having text glued to the edge of the window.
padding.x = 10
padding.y = 10

## Remove the top bar of the window that has close/minimize/maximize buttons.
decorations = "None"

## The window will be maximized on startup.
startup_mode = "Maximized"

## For macOS keyboards, keep right option to type eg `#`.
option_as_alt = "OnlyLeft"

## ─────────────────────────────────────────────────────────────────────────────
## 📄 Scrolling.
## ─────────────────────────────────────────────────────────────────────────────

[scrolling]

## Maximum history to allow long long scrolls.
history = 10000

## Scroll up/down 3 lines at a time.
multiplier = 3

## ─────────────────────────────────────────────────────────────────────────────
## 🔤 Font.
## ─────────────────────────────────────────────────────────────────────────────

[font]
size = 16

normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
