#!/usr/bin/env bash

apt_up() {
    sudo apt-get --allow-releaseinfo-change update
    sudo apt-get upgrade -y
    sudo apt-get dist-upgrade -y
    sudo apt-get autoremove --purge -y
    sudo apt-get autoclean -y
    sudo apt-get clean -y
}
alias apt_up=apt_up
