#!/usr/bin/env bash

apt_up() {
    sudo apt-get update
    sudo rm /etc/php/7.0/fpm/php.ini
    sudo apt-get upgrade -y
    sudo apt-get dist-upgrade -y
    sudo apt-get autoremove
    sudo apt-get autoclean
    sudo apt-get clean
    sudo ln -s /etc/php/7.0/cli/php.ini /etc/php/7.0/fpm/php.ini
    sudo rm /etc/php/mods-available/*0*
    sudo service php7.0-fpm restart
    sudo service nginx restart
}
alias apt_up=apt_up
