#!/bin/bash

PROJECTROOT=`echo $(cd ${0%/*}/../../ && pwd -P)`/

# Lint
if [ git lint ]; then
    echo "Aborting commit due to files with syntax errors" >&2
    exit 1
fi

# Coding Standards
RES=`php-cs-fixer fix $PROJECTROOT --verbose --dry-run --config=sf23`
if [ "$RES" != "" ]; then
    echo "Aborting commit due to failing Coding Standards" >&2
    exit 1
fi

# Tests
$PROJECTROOT/bin/tester.sh -l "$FILE" 1> /dev/null
if [ $? -ne 0 ]; then
    echo "Aborting commit due to failing tests" >&2
    exit 1
fi
