#!/usr/bin/env bash
# File: /503-sketchybar/config/sketchybarrc
# ──────────────────────────────────────────────────────────────────────────────
# 🖼️ SketchyBar
# ──────────────────────────────────────────────────────────────────────────────

## ─────────────────────────────────────────────────────────────────────────────
## ☕ Theme: homemade Catpuccin Machiatto
## ─────────────────────────────────────────────────────────────────────────────
source "${CONFIG_DIR}/themes/catppuccin-macchiato.sh"

## ─────────────────────────────────────────────────────────────────────────────
## Bar Properties. 
##
## See: https://felixkratz.github.io/SketchyBar/config/bar
## ─────────────────────────────────────────────────────────────────────────────
sketchybar --bar position=top \
                 height=35 \
                 color="${_SSDF_CM_MANTLE}"

## ─────────────────────────────────────────────────────────────────────────────
## Item Properties. 
##
## See: https://felixkratz.github.io/SketchyBar/config/items
## ─────────────────────────────────────────────────────────────────────────────
default=(
  padding_left=5
  padding_right=5
  icon.font="JetBrainsMono Nerd Font:Bold:17.0"
  label.font="JetBrainsMono Nerd Font:Bold:14.0"
  icon.color="${_SSDF_CM_SUBTEXT_1}"
  label.color="${_SSDF_CM_SUBTEXT_1}"
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

### ────────────────────────────────────────────────────────────────────────────
### Items
### ────────────────────────────────────────────────────────────────────────────
source "${CONFIG_DIR}/items/hostname.sh"
source "${CONFIG_DIR}/items/workspaces.sh"

source "${CONFIG_DIR}/items/datetime.sh"
source "${CONFIG_DIR}/items/battery.sh"
source "${CONFIG_DIR}/items/keyboard.sh"
source "${CONFIG_DIR}/items/slack.sh"

## ─────────────────────────────────────────────────────────────────────────────
## Run scripts, on initial launch.
## ─────────────────────────────────────────────────────────────────────────────
sketchybar --update
