#!/usr/bin/env bash
## Common bash function

# Allows to sudo an alias
alias sudo="sudo "

# Listing
alias ls="ls --color"
alias l="ls --color"
alias la="ls -a --color"
alias ll="ls -l --color"
alias lla="ls -la --color"

# Interractive mode
alias cp="cp -i"
alias mv="mv -i"

# Search
alias grep='grep --exclude-dir ".svn" --exclude-dir ".git" --exclude tagsi --color=tty'
alias sed="sed --follow-symlinks"

# PHP
alias s='phpspec run --format=dot'
alias d='phpspec describe'
alias u='phpunit'
alias t='u;s'
