#!/usr/bin/env bash
# Configuration

DOTBASH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

###
# Includes
###

# Custom configuration
for file in $DOTBASH/*; do
    if [ -f $file ] && [ $file != "$DOTBASH/configuration" ] ; then
        . $file
    fi
done
unset file

# Custom functions
for file in $DOTBASH/functions/*; do
  . $file
done
unset file

###
# Custom colors
###
if [[ `which dircolors` ]]; then
    if [ -f $HOME/.dir_colors ]; then
        eval `dircolors --bourne-shell $HOME/.dir_colors`
    fi
fi

###
# Shell options
###
shopt -s cdspell # Fix cd typos
shopt -s checkwinsize
shopt -s cmdhist # Log multi line commands
shopt -s expand_aliases # Replace aliases
shopt -s histappend # Append to history, instead of over writing
shopt -s nocaseglob # Case insensitive

unset DOTBASH
