#!/usr/bin/env bash
# Environment variables
export HISTSIZE=10000
export HISTFILESIZE=${HISTSIZE}
export HISTIGNORE="ls:cd:[bf]g:exit"
export HISTCONTROL="ignoreboth" # ignore duplicate line + line which start by a space

export PAGER=`which less`
export LESSOPEN="| /usr/share/source-highlight/src-hilite-lesspipe.sh %s"
export LESS="FRSX -R"

export EDITOR=`which vim`

# User binaries
if [ -d "$HOME/bin" ] ; then
    PATH="bin;vendor/bin;$HOME/bin:$PATH"
fi

# Composer binaries
if [ -d $HOME/.composer/vendor/bin ]; then
    PATH="$HOME/.composer/vendor/bin:$PATH"
fi
