#!/usr/bin/env bash
# PATH environment variable

# User scripts
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# User installed programs (eg ansible, etc)
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# composer global require bin
if [ -d "$HOME/.config/composer/vendor/bin" ] ; then
    PATH="$HOME/.config/composer/vendor/bin:$PATH"
fi

# project bin
PATH="bin:$PATH"

# project composer require bin
PATH="vendor/bin:$PATH"
