# File: /51-aerospace/config/aerospace.toml
# ──────────────────────────────────────────────────────────────────────────────
# 🌠 AeroSpace
# ──────────────────────────────────────────────────────────────────────────────

## ─────────────────────────────────────────────────────────────────────────────
## Start AeroSpace at login to macOS user sesion.
## ─────────────────────────────────────────────────────────────────────────────
start-at-login = true

## ─────────────────────────────────────────────────────────────────────────────
## Gaps between windows (inner-*) and between monitor edges (outer-*).
## ─────────────────────────────────────────────────────────────────────────────
[gaps]
    inner.horizontal = 10
    inner.vertical = 10
    outer.left = 10
    outer.bottom = 10
    outer.top = 10
    outer.right = 10

## ─────────────────────────────────────────────────────────────────────────────
## 'main' binding mode declaration
##
## See: https://nikitabobko.github.io/AeroSpace/guide#binding-modes
## ─────────────────────────────────────────────────────────────────────────────
[mode.main.binding]
    ### ────────────────────────────────────────────────────────────────────────
    ### Switch to Tile (focus to):
    ### * `Option ⌥` + `h`, `j`, `k`, `l` (LDUR)
    ###
    ### See: https://nikitabobko.github.io/AeroSpace/commands#focus
    ### ────────────────────────────────────────────────────────────────────────
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    ### ────────────────────────────────────────────────────────────────────────
    ### Move Tile:
    ### * `Option ⌥` + `Shift ⇧` + `h`, `j`, `k`, `l` (LDUR)
    ###
    ### See: https://nikitabobko.github.io/AeroSpace/commands#move
    ### ────────────────────────────────────────────────────────────────────────
    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    ### ────────────────────────────────────────────────────────────────────────
    ### Switch to Workspace:
    ### * `Option ⌥` + `1`, `2`, `3`, `4`
    ###
    ### See: https://nikitabobko.github.io/AeroSpace/commands#workspace
    ### ────────────────────────────────────────────────────────────────────────
    alt-1 = 'workspace 1' # Terminal
    alt-2 = 'workspace 2' # Browser
    alt-3 = 'workspace 3' # Communication
    alt-4 = 'workspace 4' # Music

    ### ────────────────────────────────────────────────────────────────────────
    ### Move Tile to Workspace:
    ### * `Option ⌥` + `Shift ⇧` + `1`, `2`, `3`, `4`
    ###
    ### See: https://nikitabobko.github.io/AeroSpace/commands#move-node-to-workspace
    ### ────────────────────────────────────────────────────────────────────────
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'

## ─────────────────────────────────────────────────────────────────────────────
## On open, move an application tile to its workspace:
## 1. Terminal (Alacritty)
## 2. Browser (Chrome)
## 3. Messaging (Slack)
## 4. Music (Spotify)
##
## Use command `aerospace list-apps` to find the app ID to use.
## ─────────────────────────────────────────────────────────────────────────────
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = "move-node-to-workspace 4"
