# File: /324-phpactor/config/phpactor.yml
# ──────────────────────────────────────────────────────────────────────────────
# 🅿️ Phpactor
# ──────────────────────────────────────────────────────────────────────────────

"phpunit.enabled": true
"prophecy.enabled": true
"symfony.enabled": true

"indexer.enabled_watchers":
    - "lsp"
    - "inotify"
    - "fswatch"
    - "find"
