" Convert tabs to 4 spaces
:set tabstop=4 shiftwidth=4 expandtab

" Syntax highlighting in Markdown "fenced" code blocks
let g:markdown_fenced_languages = ['php', 'sql', 'json', 'yaml']

" Plugins managed by vim-plug
call plug#begin('~/.vim/plugged')

Plug 'preservim/nerdtree'          " Tree navigation
Plug 'ctrlpvim/ctrlp.vim'          " Fuzzy finder
Plug 'shawncplus/phpcomplete.vim'  " PHP autocomplete
Plug 'ervandew/supertab'           " Autocomplete
Plug 'SirVer/ultisnips'            " Snippets

call plug#end()
